export default [
  {
    id: "Q1",
    title: "Quiz 1",
    course: "RS101",
    description: "Example quiz",
    isPublished: true,
    quizType: "Graded Quiz",
    points: 10,
    for: "Everyone",
    viewResponses: "Always",
    requireRespondus: true,
    requiredViewResults: true,
    assignmentGroup: "Quizzes",
    shuffleAnswers: false,
    timeLimit: 20,
    multipleAttempts: true,
    showCorrectAnswers: "Immediately",
    accessCode: "",
    oneQuestionAtATime: false,
    webcamRequired: false,
    lockQuestionsAfterAnswering: false,
    dueDate: "2024-04-01",
    availableDate: "2024-02-01",
    untilDate: "2024-05-01",
    questions: [
      {
        id: "q1",
        type: "Fill in the Blank",
        title: "Question 1",
        points: 1,
        question: "1+1=___. Opposite of no: ___.",
        blanks: [
          {
            id: 0,
            answer: "2",
          },
          {
            id: 1,
            answer: "yes",
          }
        ],
        choices: [],
        trueFalse: false,
      },
      {
        id: "q2",
        type: "Multiple Choice",
        title: "Question 2",
        points: 4,
        question: "What is 1+2",
        blanks: [],
        choices: [
          {
            id: 0,
            answer: "1",
            isCorrect: false,
          },
          { id: 1, answer: "3", isCorrect: true },
          { id: 2, answer: "4", isCorrect: false },
        ],
        trueFalse: false,
      },
    ],
  },
  {
    id: "Q2",
    title: "Quiz 2",
    course: "RS101",
    description: "Example quiz",
    isPublished: true,
    quizType: "Graded Quiz",
    points: 10,
    for: "Everyone",
    viewResponses: "Never",
    requireRespondus: false,
    requiredViewResults: false,
    assignmentGroup: "Quizzes",
    shuffleAnswers: false,
    timeLimit: 20,
    multipleAttempts: true,
    showCorrectAnswers: "Immediately",
    accessCode: "",
    oneQuestionAtATime: false,
    webcamRequired: false,
    lockQuestionsAfterAnswering: false,
    dueDate: "2024-04-01",
    availableDate: "2024-02-01",
    untilDate: "2024-05-01",
    questions: [
      {
        id: "q1",
        type: "Fill in the Blank",
        title: "Question 1",
        points: 1,
        question: "What is 1+1",
        blanks: [
          {
            id: 0,
            answer: "2",
          },
        ],
        choices: [],
        trueFalse: false,
      },
      {
        id: "q2",
        type: "Multiple Choice",
        title: "Question 2",
        points: 4,
        question: "What is 1+2",
        blanks: [],
        choices: [
          {
            id: 0,
            answer: "1",
            isCorrect: false,
          },
          { id: 1, answer: "3", isCorrect: true },
          { id: 2, answer: "4", isCorrect: false },
        ],
        trueFalse: false,
      },
    ],
  },
  {
    id: "Q3",
    title: "Quiz 3",
    course: "RS101",
    description: "Example quiz",
    isPublished: false,
    quizType: "Graded Quiz",
    points: 10,
    for: "Everyone",
    viewResponses: "Always",
    requireRespondus: true,
    requiredViewResults: false,
    assignmentGroup: "Quizzes",
    shuffleAnswers: false,
    timeLimit: 20,
    multipleAttempts: true,
    showCorrectAnswers: "After Grading",
    accessCode: "",
    oneQuestionAtATime: false,
    webcamRequired: false,
    lockQuestionsAfterAnswering: false,
    dueDate: "2024-04-01",
    availableDate: "2024-02-01",
    untilDate: "2024-05-01",
    questions: [
      {
        id: "q1",
        type: "Fill in the Blank",
        title: "Question 1",
        points: 1,
        question: "What is 1+1",
        blanks: [
          {
            id: 0,
            answer: "2",
          },
        ],
        choices: [],
        trueFalse: false,
      },
      {
        id: "q2",
        type: "Multiple Choice",
        title: "Question 2",
        points: 4,
        question: "What is 1+2",
        blanks: [],
        choices: [
          {
            id: 0,
            answer: "1",
            isCorrect: false,
          },
          { id: 1, answer: "3", isCorrect: true },
          { id: 2, answer: "4", isCorrect: false },
        ],
        trueFalse: false,
      },
    ],
  },
];
